name: NGINX Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar build-essential

    - name: Download NGINX source
      run: |
        wget https://nginx.org/download/nginx-1.18.0.tar.gz
        tar -zxvf nginx-1.18.0.tar.gz
        cd nginx-1.18.0
        git clone https://github.com/passwa11/nginx_shell.git
        ./configure --with-compat --add-dynamic-module=./nginx_shell/
        make modules
        
    - name: Upload so
      uses: actions/upload-artifact@v4.3.3
      with:
        name: ngx_http_cre_module.so
        path: ${{ github.workspace }}/nginx-1.18.0/objs/ngx_http_cre_module.so
